version: "3.9"

services:

  fast_pg:
    image: postgres:16.9-bookworm
    restart: always
    env_file:
      - ./.env
    
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker_entrypoint-initdb.d




name: fast_pg
      
